// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../supabase/types";

function getEnv() {
  const isBrowser = typeof window !== "undefined";

  const url = isBrowser
    ? import.meta.env.VITE_SUPABASE_URL
    : process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;

  const key = isBrowser
    ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
    : process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  return { url, key };
}

function createSupabaseClient() {
  const { url, key } = getEnv();

  if (!url || !key) {
    throw new Error("Missing Supabase environment variables.");
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
